ARG NODE_VERSION=24-slim

FROM node:${NODE_VERSION} AS dependencies


WORKDIR /app

COPY package.json  package-lock.json* ./

RUN --mount=type=cache,target=/root/.npm \
  npm ci --no-audit --no-fund

# STAGE 2
FROM node:${NODE_VERSION} AS builder
ARG NEXT_PUBLIC_API_URL
ENV NEXT_PUBLIC_API_URL=$NEXT_PUBLIC_API_URL

WORKDIR /app

COPY --from=dependencies /app/node_modules ./node_modules/

COPY . .

ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1

RUN npm run build

# STAGE 3
FROM node:${NODE_VERSION} as runner

WORKDIR /app

ENV NODE_ENV=production
ENV PORT=3000
ENV HOSTNAME="0.0.0.0"
ENV NEXT_TELEMETRY_DISABLED=1

COPY --from=builder --chown=node:node /app/public ./public

RUN mkdir .next
RUN chown node:node .next

COPY --from=builder --chown=node:node /app/.next/standalone ./
COPY --from=builder --chown=node:node /app/.next/static ./.next/static

USER node

EXPOSE 3000

CMD ["node", "server.js"]
