services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.local.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
  frontend:
    build:
      context: ./frontend
      args:
       NEXT_PUBLIC_API_URL: /backend
    image: xenozite/osu-similarity-frontend:latest
    environment:
      INTERNAL_API_URL: http://backend:8000
    depends_on:
      - backend
  backend:
    build: ./backend/
    image: xenozite/osu-similarity-backend:latest
    env_file: ./backend/.env.local
    environment:
      DATABASE_URL: ${DATABASE_URL}
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres:18
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes: [pgdata:/var/lib/postgresql]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      retries: 10

volumes:
  pgdata:
